export const routes = {
  home: '/',
  login: '/login',
  users: '/users',
  page: '/page',
  help: '/help',
  editUser: '/users/edit',
  previewUser: '/users/view',
  addUser: '/users/add',
  adminChangePassword: '/users/edit/change-password',
  contacts: '/contacts',
  addContact: '/contacts/add',
  editContact: '/contacts/edit',
  previewContact: '/contacts/view',
};
